---
# This workflow is used to build and publish a Maven project to a Maven repository (GitHub packages or Maven Central).
# It has a dry run stage to check the build process without actually publishing the artifacts.
# The workflow is triggered manually and allows the user to specify the version type (major, minor, patch), Maven profile, and additional Maven arguments.
# The workflow also creates a GitHub release after the deployment stage if the deployment is successful.
# The workflow uses the `netcracker/qubership-workflow-hub/actions/maven-release` action to perform the build and publish steps.
# The workflow requires the following inputs:
# - `version-type`: The type of version to release (major, minor, patch).
# - `maven-args`: Additional Maven arguments to pass (e.g. -DskipTests=true -Dmaven.javadoc.skip=true).
# - `profile`: The Maven profile to use (e.g. github, central).
# Please make sure to set the required secrets in your GitHub repository:
# - `GITHUB_TOKEN`: The GitHub token used for authentication.
# - `GPG_PRIVATE_KEY`: The GPG private key used for signing the artifacts.
# - `GPG_PASSPHRASE`: The passphrase for the GPG private key.
# - `MAVEN_USER`: The Maven username used for authentication (for Maven Central).
# - `MAVEN_PASSWORD`: The Maven password used for authentication (for Maven Central).
# - `GH_BUMP_VERSION_APP_ID`: The GitHub App ID used for authentication.
# - `GH_BUMP_VERSION_APP_KEY`: The private key for the GitHub App used for authentication.
# The workflow also requires the https://github.com/Netcracker/.github/blob/main/config/examples/release-drafter-config.yml config file to create a GitHub release.
# Please prepare project's pom.xml file according to https://github.com/netcracker/.github/blob/main/docs/maven-publish-pom-preparation_doc.md
# to be able to use this workflow.

name: Maven release

run-name: ${{ github.event.inputs.version-type }} release for ${{ github.event.repository.name }}

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: "Version type to release"
        type: choice
        options:
          - "major"
          - "minor"
          - "patch"
        required: true
        default: "patch"
      profile:
        description: "Maven profile to use"
        type: choice
        options:
          - "github"
          - "central"
        required: false
        default: "central"
      mvn-args:
        description: "Additional maven arguments to pass (e.g. -DskipTests=true -Dmaven.javadoc.skip=true)"
        required: false
        default: ""
        type: string
      build-docker:
        description: "Build Docker image"
        required: false
        default: true
        type: boolean
      mark-as-latest:
        description: "Mark release and Docker image if any as 'latest'"
        type: boolean
        required: false
        default: true

permissions:
  contents: read

jobs:
  dry-run-build:
    name: "Dry Run Maven Build and Publish"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Build and Publish current SNAPSHOT (dry run)"
        uses: netcracker/qubership-workflow-hub/actions/maven-release@396774180000abdb825cbf150b56cc59c6913db8 #v2.0.5
        with:
          version-type: ${{ github.event.inputs.version-type }}
          ref: ${{ github.ref }}
          module: ${{ github.event.repository.name }}
          maven-args: ${{ inputs.mvn-args }}
          profile: ${{ inputs.profile }}
          server-id: ${{ inputs.profile }}
          token: ${{ secrets.GITHUB_TOKEN }}
          maven-user: ${{ inputs.profile == 'github' && github.actor || secrets.MAVEN_USER }}
          maven-password: ${{ inputs.profile == 'github' && secrets.GITHUB_TOKEN || secrets.MAVEN_PASSWORD }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          dry-run: "true"
  deploy:
    name: "Maven Build and Publish"
    needs: [dry-run-build]
    if: ${{ needs.dry-run-build.result == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      release-version: ${{ steps.build-and-publish.outputs.release-version }}
    steps:
      # This step is needed if there is a GitHub App used for authentication to bypass the protected branch rule
      - name: "Prepare app token"
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ vars.GH_BUMP_VERSION_APP_ID }}
          private-key: ${{ secrets.GH_BUMP_VERSION_APP_KEY }}

      - name: "Build and Publish"
        id: build-and-publish
        uses: netcracker/qubership-workflow-hub/actions/maven-release@396774180000abdb825cbf150b56cc59c6913db8 #v2.0.5
        with:
          version-type: ${{ github.event.inputs.version-type }}
          ref: ${{ github.ref }}
          module: ${{ github.event.repository.name }}
          maven-args: ${{ inputs.mvn-args }}
          profile: ${{ inputs.profile }}
          server-id: ${{ inputs.profile }}
          token: ${{ steps.app-token.outputs.token }} # It can be ${{ secrets.GITHUB_TOKEN }} if default branch isn't protected
          maven-user: ${{ inputs.profile == 'github' && github.actor || secrets.MAVEN_USER }}
          maven-password: ${{ inputs.profile == 'github' && secrets.GITHUB_TOKEN || secrets.MAVEN_PASSWORD }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          dry-run: "false"

      - name: "Upload all Maven target directories"
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ github.event.repository.name }}
          path: "${{ github.event.repository.name }}/**/target" # Upload all target directories in the repository
  check-dockerfile:
    name: "Check Dockerfile Existence"
    needs: [deploy]
    if: ${{ github.event.inputs.build-docker == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      dockerfile_exists: ${{ steps.check_dockerfile.outputs.df_exists }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: "Check Dockerfile existence"
        id: check_dockerfile
        shell: bash
        run: |
          if [[ -f Dockerfile ]]; then
            echo "df_exists=exists" >> "$GITHUB_OUTPUT"
          else
            echo "Dockerfile does not exist. Docker build stage will be skipped"
            echo "df_exists=notexists" >> "$GITHUB_OUTPUT"
          fi
          echo "GITHUB_OUTPUT:"
          cat "$GITHUB_OUTPUT"

  docker-build:
    name: "Docker Build and Publish"
    if: ${{ github.event.inputs.build-docker == 'true' && needs.check-dockerfile.outputs.dockerfile_exists == 'exists' }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    needs: [check-dockerfile, deploy]
    steps:
      - name: "Prepare Docker tags"
        if: ${{ github.event.inputs.mark-as-latest != 'true' }}
        id: meta
        uses: netcracker/qubership-workflow-hub/actions/metadata-action@396774180000abdb825cbf150b56cc59c6913db8 #v2.0.5
        with:
          default-template: "{{major}}.{{minor}}.{{patch}},{{major}}.{{minor}},{{major}}"
          ref: ${{ needs.deploy.outputs.release-version }}
          default-tag: ${{ needs.deploy.outputs.release-version }}
      - name: Set env
        if: ${{ github.event.inputs.mark-as-latest != 'true' }}
        run: |
          echo "TAGS=$META_STEP_RESULT" >> $GITHUB_ENV
        env:
          META_STEP_RESULT: ${{ steps.meta.outputs.result }}

      - name: "Docker Build"
        id: docker_build
        uses: netcracker/qubership-workflow-hub/actions/docker-action@396774180000abdb825cbf150b56cc59c6913db8 #v2.0.5
        with:
          ref: v${{ needs.deploy.outputs.release-version }}
          download-artifact: true
          tags: ${{ env.TAGS }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

  github-release:
    name: "Create GitHub Release"
    needs: [deploy]
    permissions:
      contents: write
    if: ${{ needs.deploy.result == 'success' }}
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@396774180000abdb825cbf150b56cc59c6913db8 #v2.0.5
    with:
      version: ${{ needs.deploy.outputs.release-version }}
      publish: true
      latest: "${{ inputs.mark-as-latest }}"
